version: '3'

services:
  backend:
    container_name: backend
    image: app_java:latest
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hoteles
